# Generated by Django 3.1.2 on 2020-10-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('pic', models.ImageField(blank=True, upload_to='images/')),
            ],
            options={
                'db_table': 'CRUDemployee',
            },
        ),
    ]
